name: Swift build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Analytico build
      run: swift build -v

# Add tests later
#    - name: Test suite
#      run: swift test -v
